// Shared between the upload/serve routes, next.config.ts and the admin UI, so
// keep this module client-safe (no node: imports).

export const UPLOAD_LIMIT = 20;
export const MAX_UPLOAD_BYTES = 2 * 1024 * 1024;

// Uploads are stored in the database and served by /api/product-image/<id>.
export const IMAGE_ROUTE_PREFIX = "/api/product-image/";
// Uploads made before that, written into public/images/product, are still
// served statically from the repo.
export const LEGACY_UPLOAD_PREFIX = "/images/product/";

export const EXT_BY_MIME: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/avif": "avif",
};

/** An image we host ourselves, as opposed to a URL the admin pasted in. */
export function isUploadedImage(src: string | undefined): boolean {
  if (!src) return false;
  return (
    src.startsWith(IMAGE_ROUTE_PREFIX) ||
    src.startsWith(LEGACY_UPLOAD_PREFIX) ||
    src.startsWith("data:")
  );
}

// Ids are generated by the upload route, but they arrive back as URL segments
// and as file names in the dev fallback, so keep them strictly alphanumeric.
export function isValidImageId(id: string): boolean {
  return /^[A-Za-z0-9_-]{1,64}$/.test(id);
}

/** The stored-image id behind a product image URL, or null for anything else. */
export function imageIdFromUrl(src: string | undefined): string | null {
  if (!src?.startsWith(IMAGE_ROUTE_PREFIX)) return null;
  const id = src.slice(IMAGE_ROUTE_PREFIX.length);
  return isValidImageId(id) ? id : null;
}

export function imageUrl(id: string): string {
  return `${IMAGE_ROUTE_PREFIX}${id}`;
}

// Remote hosts the Next.js image optimizer is allowed to fetch from. next.config.ts
// turns this into images.remotePatterns, so the two can't drift apart.
export const OPTIMIZED_IMAGE_HOSTS = [
  "images.unsplash.com",
  "plus.unsplash.com",
  "i.pravatar.cc",
];

/**
 * Whether next/image may run this src through the optimizer.
 *
 * Admins paste image URLs from anywhere (Google image results, supplier sites),
 * and the optimizer hard-errors on any host missing from remotePatterns. We
 * can't allowlist the whole internet — that would make /_next/image an open
 * proxy — so unknown hosts get rendered as-is instead. See SmartImage.
 */
export function isOptimizableImage(src: unknown): boolean {
  // Static imports (`import pic from "./pic.png"`) are bundled by us.
  if (typeof src !== "string") return true;
  // Same-origin paths, including our own /api/product-image/<id> uploads.
  if (src.startsWith("/") && !src.startsWith("//")) return true;
  // next/image already forces these unoptimized.
  if (src.startsWith("data:") || src.startsWith("blob:")) return true;
  try {
    return OPTIMIZED_IMAGE_HOSTS.includes(new URL(src).hostname);
  } catch {
    // Protocol-relative or otherwise unparseable — let the browser deal with it.
    return false;
  }
}
